# Generated by Django 2.0.4 on 2018-08-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gs_schdl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title of production')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_schdl.Production')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title of production')),
                ('members', models.ManyToManyField(to='gs_schdl.Member')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_schdl.Production')),
            ],
        ),
    ]
